### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by xinthose** [Azure/iisnode#135]
Should I be using this in production if it has not had a new release in over 6 years?

**Comment by Choomai** [comment]
I've been using it for a year now, and nothing has happened (I use `express` and `socket.js`, which work as intended).
But maybe you shouldn't. Just listen on a random port and make IIS a reverse proxy. I've never experienced anything like authorization, just some small projects or APIs that won't require auth.

**Comment by xinthose** [comment]
@Choomai OK.  Thank you.
