### ISSUE TITLE
Can't install at Windows 10

### ISSUE THREAD

**Issue by keke78ui9** [Azure/iisnode#29]
display 'iis7.x or later must be installed before iisnode installation' when run iisnode-full-v0.2.11-x64.msi at windows 10 Home

**Comment by berlamont** [comment]
Same here, is IIS 10 going to be supported soon??

**Comment by rramachand21** [comment]
Please look at https://github.com/tjanczuk/iisnode/issues/450

**Comment by CoderMonkie** [comment]
I can't install by 'Web Platform Installer'.

![cannot-install-iisnode-for-iis](https://user-images.githubusercontent.com/26118847/59481937-17167900-8e99-11e9-997d-48a0563584c4.png)

---

then turn to: tjanczuk#450
by downloading the msi file, I installed successfully.
