### ISSUE TITLE
Support Meteor projects

### ISSUE THREAD

**Issue by adaptabi** [Azure/iisnode#30]
Currently there is no real way of deploying `METEOR` projects to windows world.
Would be great if `IISNODE` would support them out of the box.

**Comment by rramachand21** [comment]
You can deploy it with iisnode by removing the parseInt(port) in the meteor core -- please see - https://github.com/tjanczuk/iisnode/issues/449

**Comment by rramachand21** [comment]
Actual issue is that meteor assumes ports to be numbers - https://github.com/meteor/meteor/issues/4413

**Comment by ramijarrar** [comment]
I think this can be closed now, meteor/meteor#4413 has been addressed and we haven't run into any other issues with Meteor deployments.

**Comment by ramijarrar** [comment]
On a side-note: Meteor depends on session affinity, and will need something like #31 to be integrated before we can support multi-core out of the box
