### ISSUE TITLE
IISNode responds with HTTP500.1013 after subsequent requests with long processing time (around > 5 seconds) 

### ISSUE THREAD

**Issue by j-windsor** [Azure/iisnode#45]
# Repro Steps

Using Azure AppService with Node v8.0.0, IISNode v0.2.21
Using default settings in IISNode, Web.config. No iisnode.yml

### Producer (server.js)
```javascript
var http = require('http');
http.createServer(function (req, res) {
    setTimeout(() => {
        res.writeHead(200, {'Content-Type': 'text/html'});
        res.write('hi');
        res.end();
    }, 6000);
}).listen(process.env.PORT);
````

### Consumer (tester.py)
```python
import requests
import time

for i in range(0, 10):
    t0 = time.time()
    r = requests.get('https://***.azurewebsites.net/hi')
    t1 = time.time()
    print(str(r.status_code) + " in " + str(t1-t0) + "ms")
```

### Output
```
200 in 6.27462887764ms
500 in 5.32504105568ms
200 in 6.14366197586ms
500 in 5.32526397705ms
200 in 6.14505696297ms
500 in 5.32463908195ms
200 in 6.14349889755ms
500 in 5.32335090637ms
200 in 6.34911417961ms
500 in 5.324187994ms
```

**Comment by prashanthmadi** [comment]
Yep. I'm able to repro issue with node v8.0.0.. 

Try using newer version of nodejs and it works fine for me with above code..

Below link should help you change nodejs version.
https://blogs.msdn.microsoft.com/azureossds/2016/04/20/nodejs-and-npm-versions-on-azure-app-services/

**Comment by j-windsor** [comment]
Seems to work for me as well! Thanks for the fix! Azure should make sure AppService defaults to a working version of Node.
