### ISSUE TITLE
Request: Documentation Update for Debugging

### ISSUE THREAD

**Issue by mattezell** [Azure/iisnode#63]
Currently, many users are finding it difficult to work with IISNode for a number of reasons. 

One of the reasons users are experiencing problems is as a result of the fragmentation created by the original (no longer maintained) repo not directing users to this repo. In hopes of making this a bit better, I've reached out to the author on Twitter to see if he'd consider updating the readme to do that. I chose to reach out on Twitter because it seems that the author is active there, while no longer replying to issues in the original repo. 

Another problem is the accuracy of the documentation - including documentation in this Azure repo.  For example, the "NEW: integrated debugging with node-inspector v0.7.3" link takes you to a product sales site, which does not instill confidence in users when they find themselves referencing the IISNode documentation here in the official Azure repo.

Something else that would improve user's experiences would be to update the documentation with updated debugging guidance.  For example, I've successfully setup debugging in VSCode against an IISNode hosted NestJS/Express application, as I've detailed here: https://github.com/Azure/iisnode/issues/54#issuecomment-423561880 I would propose this be included in the documentation. I would be happy to write this process up more formally if that would be of assistance to this project.

**Comment by mattezell** [comment]
Update on this. The original repo has been updated to direct user's here.

https://github.com/tjanczuk/iisnode

Thanks @tjanczuk!

**Comment by mattezell** [comment]
I've written a post on my personal blog detailing how to debug an IISNode hosted application via VSCode: https://blog.immatt.com/2018/10/09/iisnode-modern-debugging-via-vscode/

Any interest in including this in the docs?

**Comment by davidebbo** [comment]
Yeah, looks like solid content! Send PR to add link?

**Comment by mattezell** [comment]
Thanks, @davidebbo - I've submitted a PR which removes the bad debugging link and adds this one.. https://github.com/Azure/iisnode/pull/66

**Comment by davidebbo** [comment]
Done deal, thanks for the post!
