### ISSUE TITLE
IISnode is killing nodejs service process

### ISSUE THREAD

**Issue by NoelAbrahams** [Azure/iisnode#91]
Copied over from https://github.com/tjanczuk/iisnode/issues/569

Still an issue in 2020.

-----------------------------------------
Hi,

I'm are having issues with my node.js service running on IIS with iisnode. The problem is that nodejs service process is being killed and iis starts a new process, and that happens every time my node.js service is processing some request. My node.js service is doing lots of files downloading and lots of changes and validations on those files and also creating new ones,
This process requires lots of memory and writing to disk.

Then, if some GET request is sent to my service, in the middle of processing those files, or downloading files, nodejs process is killed, and IIS Node starts new process.

THe big problem here is that I don't get any exceptions and can not figure out why this happens..

When I test the service running as plain node.js service, (without IIS), it works fine. No stopping of service happened and it handled all requests.

I'm using:

iisnode version 0.2.21 full IIS 7.x (x64) (also tried with 0.2.26)
node version 4.6.0 (x64)
rewrite 2.0 rtw x64
IIS on Windows 7, x64 version 7.5.7600
IIS on Win Server 2012 R2 version 8.5.9600
Do you have suggestion how to solve this, and also is it possible to turn on some logging on iisnode?
I have already turned on debuggingEnabled="true" loggingEnabled="true" devErrorsEnabled="true" but there is no errors in log folder.

Thanks!

---------------------------------------------

**Comment by IllusionVK** [comment]
Hi @NoelAbrahams, is it the app pool being reycled by IIS ?  and you're running a reaaaaly old version of node...  Have you tried like v12 ?

**Comment by NoelAbrahams** [comment]
Hi @IllusionVK it's not the IIS app pool since we have configured IIS to disable recycling. 

I raised this issue when we were investigating some persistent problems with our connectivity. This particular issue was traced to another source. However, the fact that IISNode is a black box is still a problem. It's difficult to eliminate it altogether from the troubleshooting since there is no logging of what goes on inside IIS Node.

I'm closing this as I am no longer able to say that this is a problem.

**Comment by djsavvy** [comment]
@NoelAbrahams what was the source of this issue in the end? We have been dealing with intermittent, unlogged restarts in our IISNode app for a couple years now and have no idea what is causing them

**Comment by NoelAbrahams** [comment]
@djsavvy sorry, could not find the exact details since we seem to have carried out a number of changes. These included consolidating multiple IIS App Pools into one and improving the performance of NodeJS module loading.

**Comment by djsavvy** [comment]
@NoelAbrahams  no worries! Thanks for following up, this is already quite helpful.
